update makefile to run A2 tests

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -12,10 +12,10 @@ style: shell.c shell.h interpreter.c interpreter.h shellmemory.c shellmemory.h
 clean: 
 	$(RM) mysh; $(RM) *.o; $(RM) *~
 
-test: mysh
+testA1: mysh
 	@for t in badcommand echo ls mkdir oneline oneline2 prompt run set source; do \
-		cd ../test-cases && ../src/mysh < $$t.txt > result.tmp; \
-		diff -w -q ../test-cases/result.tmp ../test-cases/$${t}_result.txt > /dev/null; \
+		cd ../test-cases-A1 && ../src/mysh < $$t.txt > result.tmp; \
+		diff -w -q ../test-cases-A1/result.tmp ../test-cases-A1/$${t}_result.txt > /dev/null; \
 		if [ $$? -eq 0 ]; then \
 			echo "$$t: PASS"; \
 		else \
@@ -23,3 +23,14 @@ test: mysh
 		fi; \
 	done
 	@rm -f result.tmp
+
+testA2: mysh
+	@for t in T_AGING T_AGING2 T_AGING3 T_AGING4 T_background T_FCFS T_FCFS2 T_FCFS3 T_FCFS4 T_RR T_RR2 T_RR3 T_RR4 T_RR30 T_RR30_2 T_SJF T_SJF2 T_SJF3 T_SJF4 T_source; do \
+		cd ../test-cases-A2 && ../src/mysh < $$t.txt > result.tmp; \
+		diff -w -q ../test-cases-A2/result.tmp ../test-cases-A2/$${t}_result.txt > /dev/null; \
+		if [ $$? -eq 0 ]; then \
+			echo "$$t: PASS"; \
+		else \
+			echo "$$t: FAIL"; \
+		fi; \
+	done
