move test cases to their own folder + update automated test script

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -14,9 +14,12 @@ clean:
 
 test: mysh
 	@for t in badcommand echo ls mkdir oneline oneline2 prompt run set source; do \
-		./mysh < $$t.txt > my_res.tmp; \
-		diff -w -q my_res.tmp $${t}_result.txt > /dev/null; \
-		if [ $$? -eq 0 ]; then echo "$$t: PASS"; else echo "$$t: FAIL"; fi; \
+		./mysh < ../test-cases/$$t.txt > result.tmp; \
+		diff -w -q result.tmp ../test-cases/$${t}_result.txt > /dev/null; \
+		if [ $$? -eq 0 ]; then \
+			echo "$$t: PASS"; \
+		else \
+			echo "$$t: FAIL"; \
+		fi; \
 	done
-	@rm -f my_res.tmp
-
+	@rm -f result.tmp
