debugging

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -26,14 +26,21 @@ testA1: mysh
 
 testA2: mysh
 	@for t in $$(cd ../test-cases-A2 && ls T_*.txt | grep -v '_result' | sed 's/.txt//'); do \
-		cd ../test-cases-A2 && ../src/mysh < $$t.txt > result.tmp; \
-		diff -w -q ../test-cases-A2/result.tmp ../test-cases-A2/$${t}_result.txt > /dev/null; \
-		if [ $$? -eq 0 ]; then \
-			echo "$$t: PASS"; \
-		elif [ -f $${t}_result2.txt ] && diff -w -B -q result.tmp $${t}_result2.txt > /dev/null; then \
-			echo "$$t: PASS (Matches Result 2)"; \
+		(cd ../test-cases-A2 && ../src/mysh < $$t.txt > result.tmp; \
+		if echo $$t | grep -q "^T_MT"; then \
+			[ $$(grep -o "X" result.tmp | wc -l) -eq $$(grep -o "X" $${t}_result.txt | wc -l) ] && \
+			[ $$(grep -o "YY" result.tmp | wc -l) -eq $$(grep -o "YY" $${t}_result.txt | wc -l) ] && \
+			[ $$(grep -o "ZZZ" result.tmp | wc -l) -eq $$(grep -o "ZZZ" $${t}_result.txt | wc -l) ]; \
+			if [ $$? -eq 0 ]; then echo "$$t: PASS"; else echo "$$t: FAIL"; fi; \
 		else \
-			echo "$$t: FAIL"; \
-			diff -y result.tmp $${t}_result.txt; \
-		fi; \
+			diff -w -q ../test-cases-A2/result.tmp ../test-cases-A2/$${t}_result.txt > /dev/null; \
+			if [ $$? -eq 0 ]; then \
+				echo "$$t: PASS"; \
+			elif [ -f $${t}_result2.txt ] && diff -w -B -q result.tmp $${t}_result2.txt > /dev/null; then \
+				echo "$$t: PASS (Matches Result 2)"; \
+			else \
+				echo "$$t: FAIL"; \
+				# diff -y result.tmp $${t}_result.txt; \
+			fi; \
+		fi); \
 	done
